# render.yaml
services:
  # Backend (Node.js)
  - type: web
    name: collegedunia-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      NODE_VERSION: 22.20.0
      PORT: 4001
      MONGO_URI: "mongodb+srv://admin:admin123@clusterone.mym38ni.mongodb.net/collegedunia?retryWrites=true&w=majority"
      CLOUDINARY_CLOUD_NAME: your_name
      CLOUDINARY_API_KEY: "123456789"
      CLOUDINARY_API_SECRET: your_secret
      ACCESS_SECRET: superstrongsecret123
      REFRESH_SECRET: anotherstrongsecret456

  # Frontend (React + Vite)
  - type: web
    name: collegedunia-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /**
        destination: /index.html